# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_xtrac.R or similar files

#' @name testinput_xtrac
#' @docType data
#' @title for internal use
'testinput_xtrac'
